/**
 * MachineAlertsApi
 *
 * Auto-generated SDK wrapper for John Deere machine-alerts API.
 * @generated from machine-alerts.yaml
 */

import type { DeereClient, PaginatedResponse, RequestOptions } from '../client.js';
import type { components } from '../types/generated/machine-alerts.js';

export class MachineAlertsApi {
  constructor(private readonly client: DeereClient) {}

  /**
   * Alerts
   * @description The alerts service allows clients to retrieve the information
   * captured on the terminal when an alert occurred. For example, an alert is
   * generated by a machine when the fuel pressure is low or there is a
   * calibration fault in the fuel injector.Various alert types include machine,
   * geofence, and maintenance. Response details will vary based on the alert
   * type, which you can find in the links. Some responses will contain a
   * "definition" that will give further information, see below. For each alert,
   * the response links to the following resources: machine: View machine
   * information
   * @generated from GET /machines/{principalId}/alerts
   */
  async list(
    principalId: string,
    params?: { startDate?: string; endDate?: string; excludeAcknowledged?: boolean },
    options?: RequestOptions
  ): Promise<PaginatedResponse<components['schemas']['AlertValue']>> {
    const query = new URLSearchParams();
    if (params?.startDate !== undefined) query.set('startDate', String(params.startDate));
    if (params?.endDate !== undefined) query.set('endDate', String(params.endDate));
    if (params?.excludeAcknowledged !== undefined)
      query.set('excludeAcknowledged', String(params.excludeAcknowledged));
    const queryString = query.toString();
    const path = `/machines/${principalId}/alerts${queryString ? `?${queryString}` : ''}`;
    return this.client.get<PaginatedResponse<components['schemas']['AlertValue']>>(path, options);
  }
  /**
   * Get all items (follows pagination automatically)
   * @generated from GET /machines/{principalId}/alerts
   */
  async listAll(
    principalId: string,
    params?: { startDate?: string; endDate?: string; excludeAcknowledged?: boolean },
    options?: RequestOptions
  ): Promise<components['schemas']['AlertValue'][]> {
    const query = new URLSearchParams();
    if (params?.startDate !== undefined) query.set('startDate', String(params.startDate));
    if (params?.endDate !== undefined) query.set('endDate', String(params.endDate));
    if (params?.excludeAcknowledged !== undefined)
      query.set('excludeAcknowledged', String(params.excludeAcknowledged));
    const queryString = query.toString();
    const path = `/machines/${principalId}/alerts${queryString ? `?${queryString}` : ''}`;
    return this.client.getAll<components['schemas']['AlertValue']>(path, options);
  }
}

// Re-export types for convenience
export type { components as MachineAlertsTypes } from '../types/generated/machine-alerts.js';
