/**
 * ProductsApi
 *
 * Auto-generated SDK wrapper for John Deere products API.
 * @generated from products.yaml
 */

import type { DeereClient, RequestOptions, PaginatedResponse } from '../client.js';
import type { components } from '../types/generated/products.js';

export class ProductsApi {
  constructor(private readonly client: DeereClient) {}

  /**
   * View varieties for an org
   * @description This endpoint will retrieve a collection of varieties for the specified org.
   * @generated from GET /organizations/{organizationId}/varieties
   */
  async list(organizationId: string, params?: { status?: 'AVAILABLE' | 'ARCHIVED' | 'ALL'; embed?: 'documents' | 'showMergedProducts' }, options?: RequestOptions): Promise<PaginatedResponse<components['schemas']['VarietyCollection']>> {
    const query = new URLSearchParams();
    if (params?.status !== undefined) query.set('status', String(params.status));
    if (params?.embed !== undefined) query.set('embed', String(params.embed));
    const queryString = query.toString();
    const path = `/organizations/${organizationId}/varieties${queryString ? `?${queryString}` : ''}`;
    return this.client.get<PaginatedResponse<components['schemas']['VarietyCollection']>>(path, options);
  }
  /**
   * Get all items (follows pagination automatically)
   * @generated from GET /organizations/{organizationId}/varieties
   */
  async listAll(organizationId: string, params?: { status?: 'AVAILABLE' | 'ARCHIVED' | 'ALL'; embed?: 'documents' | 'showMergedProducts' }, options?: RequestOptions): Promise<components['schemas']['VarietyCollection'][]> {
    const query = new URLSearchParams();
    if (params?.status !== undefined) query.set('status', String(params.status));
    if (params?.embed !== undefined) query.set('embed', String(params.embed));
    const queryString = query.toString();
    const path = `/organizations/${organizationId}/varieties${queryString ? `?${queryString}` : ''}`;
    return this.client.getAll<components['schemas']['VarietyCollection']>(path, options);
  }

  /**
   * Add a variety
   * @description This endpoint will add a custom variety into the organization. Its name+cropName must be unique within your organization. Its crop name must be a supported crop name (see /cropTypes). There are a number of crop names that are deprecated in the system. If the crop name is set to one of these, then it will be mapped to its corresponding valid crop name. </br> </br> Additionally, POST can be used for supporting offline creation of varieties from e.g. a mobile app, by sending a payload  with an `id` generated by the client. If an `id` is present in the payload, the service checks the database for that `id`.</br> </br> In case no record is found, a new one is created with that `id` and the request is responded with 201.</br> Otherwise no creation happens and the request is responded with 409 and error message that a resource with that `id` already exists.
   * @generated from POST /organizations/{organizationId}/varieties
   */
  async create(organizationId: string, data: Record<string, unknown>, options?: RequestOptions): Promise<void> {
    const path = `/organizations/${organizationId}/varieties`;
    await this.client.post(path, data, options);
  }

  /**
   * View a specific variety
   * @description This endpoint will return the variety with the specified erid.
   * @generated from GET /organizations/{organizationId}/varieties/{erid}
   */
  async get(organizationId: string, erid: string, params?: { embed?: 'documents' | 'showMergedProducts' }, options?: RequestOptions): Promise<components['schemas']['Variety']> {
    const query = new URLSearchParams();
    if (params?.embed !== undefined) query.set('embed', String(params.embed));
    const queryString = query.toString();
    const path = `/organizations/${organizationId}/varieties/${erid}${queryString ? `?${queryString}` : ''}`;
    return this.client.get<components['schemas']['Variety']>(path, options);
  }

  /**
   * Update a single variety
   * @description This endpoint allows the custom variety to be renamed, made active/archived, or associated to a different manufacturer or crop type.
   * @generated from PUT /organizations/{organizationId}/varieties/{erid}
   */
  async update(organizationId: string, erid: string, data: Record<string, unknown>, options?: RequestOptions): Promise<void> {
    const path = `/organizations/${organizationId}/varieties/${erid}`;
    await this.client.put(path, data, options);
  }

  /**
   * Adds a single reference variety to organization
   * @description This endpoint will associate a reference variety to your organization from the global reference list.
   * @generated from POST /varieties/{erid}/associateToOrg/{organizationId}
   */
  async createAssociatetoorg(erid: string, organizationId: string, data: Record<string, unknown>, options?: RequestOptions): Promise<void> {
    const path = `/varieties/${erid}/associateToOrg/${organizationId}`;
    await this.client.post(path, data, options);
  }

  /**
   * Search reference catalog varieties
   * @description This endpoint searches the reference catalog for varieties that match the given search criteria. This data can be used in a subsequent request to create a variety in an organization. Results are limited to 100 items.
   * @generated from GET /varieties
   */
  async listVarieties(params?: { searchString?: string; cropName?: string; productName?: string; brandName?: string; sourceSystemProductId?: string; countryCode?: string }, options?: RequestOptions): Promise<PaginatedResponse<components['schemas']['ReferenceVarietyCollection']>> {
    const query = new URLSearchParams();
    if (params?.searchString !== undefined) query.set('searchString', String(params.searchString));
    if (params?.cropName !== undefined) query.set('cropName', String(params.cropName));
    if (params?.productName !== undefined) query.set('productName', String(params.productName));
    if (params?.brandName !== undefined) query.set('brandName', String(params.brandName));
    if (params?.sourceSystemProductId !== undefined) query.set('sourceSystemProductId', String(params.sourceSystemProductId));
    if (params?.countryCode !== undefined) query.set('countryCode', String(params.countryCode));
    const queryString = query.toString();
    const path = `/varieties${queryString ? `?${queryString}` : ''}`;
    return this.client.get<PaginatedResponse<components['schemas']['ReferenceVarietyCollection']>>(path, options);
  }

  /**
   * Get a single reference variety.
   * @description Single variety from industry data sources, such as CDMS.
   * @generated from GET /varieties/{erid}
   */
  async getVarieties(erid: string, options?: RequestOptions): Promise<components['schemas']['ReferenceVariety']> {
    const path = `/varieties/${erid}`;
    return this.client.get<components['schemas']['ReferenceVariety']>(path, options);
  }

  /**
   * Reference list of documents for an associated seed variety.
   * @description List of all the documents for a variety from industry data sources, such as CDMS.
   * @generated from GET /varieties/{erid}/documents
   */
  async listDocuments(erid: string, options?: RequestOptions): Promise<PaginatedResponse<components['schemas']['DocumentCollection']>> {
    const path = `/varieties/${erid}/documents`;
    return this.client.get<PaginatedResponse<components['schemas']['DocumentCollection']>>(path, options);
  }

  /**
   * Sets organizational attributes such as isCarrier, archived, registration, etc.
   * @description This endpoint will set attribute overrides while importing a reference variety to your organization. The reference varieties are immutable, however, they can still be archived or made available. The response headers from the GET endpoints will include the attributes that can be overridden.
   * @generated from PATCH /varieties/{erid}/setOverridesForOrg/{organizationId}
   */
  async patch(erid: string, organizationId: string, data: Record<string, unknown>, options?: RequestOptions): Promise<void> {
    const path = `/varieties/${erid}/setOverridesForOrg/${organizationId}`;
    await this.client.patch(path, data, options);
  }
}

// Re-export types for convenience
export type { components as ProductsTypes } from '../types/generated/products.js';
