/**
 * The routing snapshot: every path the SDK ships, and the base URL it resolves
 * to. Committed, regenerated by `pnpm generate-routing-snapshot`, and enforced
 * by tests/routing-snapshot.test.ts.
 *
 * This is scripts/api-surface.yaml for URLs. That manifest exists so an
 * upstream reorder cannot silently rebind a published method name; this exists
 * so a change anywhere in the pipeline cannot silently rebind a published
 * method's host. Both make an invisible change land as a reviewable diff.
 *
 * The hand-picked URL assertions in tests/generate-api-servers.test.ts and
 * tests/environment-resolver.test.ts cover a handful of specs deliberately.
 * This covers all 121 paths mechanically, which is the difference between
 * catching a regression in the spec you thought about and catching one in the
 * spec you did not.
 *
 * NOTE: this module imports from src/. It is the only script that does, and
 * deliberately: the snapshot's whole purpose is pinning what the RUNTIME
 * resolves, so it has to go through resolveRequestUrl rather than re-deriving
 * the answer from the specs and hoping the two agree.
 */

import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import * as yaml from 'yaml';
import type { Environment, SpecName } from '../../src/api-servers.generated.js';
import { resolveRequestUrl } from '../../src/environment-resolver.js';

const SPECS_DIR = join(process.cwd(), 'specs', 'fixed');

export const SNAPSHOT_PATH = join(process.cwd(), 'scripts', 'routing-snapshot.yaml');

/**
 * One canonical environment. Templated specs resolve identically across
 * environments modulo substitution, and the per-environment maps of the three
 * static specs are already pinned in tests/generate-api-servers.test.ts, so a
 * second column here would add length without adding coverage.
 */
const SNAPSHOT_ENVIRONMENT: Environment = 'api';

const HEADER = `# Routing snapshot — scripts/routing-snapshot.yaml
#
# GENERATED by \`pnpm generate-routing-snapshot\`. Do not hand-edit.
#
# Every path the SDK ships, and the base URL resolveRequestUrl sends it to in
# the "${SNAPSHOT_ENVIRONMENT}" environment. tests/routing-snapshot.test.ts fails when this
# file disagrees with what the code actually resolves, so any change to URL
# construction has to land here as a reviewable diff rather than shipping
# unnoticed.
#
# A diff in this file is not automatically wrong. It means a published method
# changed host, which is exactly the kind of change that should need a human to
# look at it. Regenerate, read the diff, and confirm each moved path is
# intentional and measured before committing.
#
# Entries whose base is not the platform host are the interesting ones. They
# come from a spec's own servers block (equipment and aemp live elsewhere by
# design) or from scripts/routing-overrides.yaml, where each carries recorded
# evidence.

`;

export interface RoutingSnapshotRow {
  spec: string;
  path: string;
  /** Base URL, i.e. the resolved URL with the path suffix removed. */
  base: string;
}

/** Substituted into `{param}` segments; the value cannot affect resolution. */
const PARAM_PLACEHOLDER = '_';

function fillParams(path: string): string {
  return path.replace(/\{[^}]+\}/g, PARAM_PLACEHOLDER);
}

/**
 * Resolve every path in every fixed spec. Specs that cannot resolve the
 * canonical environment are skipped and reported, not silently dropped: the
 * three static specs legitimately refuse environments they have no tier for.
 */
export function buildRoutingSnapshot(): { rows: RoutingSnapshotRow[]; skipped: string[] } {
  const rows: RoutingSnapshotRow[] = [];
  const skipped: string[] = [];

  for (const file of readdirSync(SPECS_DIR)
    .filter((f) => f.endsWith('.yaml'))
    .sort()) {
    const spec = file.replace(/\.yaml$/, '');
    const doc = yaml.parse(readFileSync(join(SPECS_DIR, file), 'utf-8'));

    for (const path of Object.keys(doc?.paths ?? {}).sort()) {
      const concrete = fillParams(path);
      let url: string;
      try {
        url = resolveRequestUrl(spec as SpecName, concrete, SNAPSHOT_ENVIRONMENT);
      } catch (error) {
        skipped.push(
          `${spec} ${path}: ${error instanceof Error ? error.message.split('\n')[0] : error}`
        );
        continue;
      }
      if (!url.endsWith(concrete)) {
        throw new Error(
          `routing-snapshot: resolved URL ${url} does not end with the path ${concrete} it was ` +
            `built from, so the base cannot be recovered. resolveRequestUrl's contract changed.`
        );
      }
      rows.push({ spec, path, base: url.slice(0, url.length - concrete.length) });
    }
  }

  return { rows, skipped };
}

export function serializeRoutingSnapshot(rows: readonly RoutingSnapshotRow[]): string {
  const routes: Record<string, Record<string, string>> = {};
  for (const row of rows) {
    const bySpec = routes[row.spec] ?? {};
    bySpec[row.path] = row.base;
    routes[row.spec] = bySpec;
  }
  const body = yaml.stringify(
    { version: 1, environment: SNAPSHOT_ENVIRONMENT, routes },
    {
      lineWidth: 0,
    }
  );
  return `${HEADER}${body}`;
}

export function readRoutingSnapshot(path: string = SNAPSHOT_PATH): string {
  return readFileSync(path, 'utf-8');
}
