openapi: "3.0.0"
info:
  description: "This set of endpoints is dealing with flags, which are pointers to a geographical location in a field or around a field which are marked for attention or treatment in a specific way.

    Flag resource is uniquely identified by its id, the endpoint /flags/{id} will be used to work with individual flag instances.


    The following flag types are supported by this API:

    - FLAG - Flags are digital markers the user places at a location marking it for (future) attention or treatment in a specific way. It is \"setup\" master data which can be exported to machine displays. Flags created on machine displays are represented as FLAG-type flags.

    - SCOUT - Scouting note which is a geo-referenced observation of certain facts within a field or outside of it. Scouting notes are essentially documentation, just as Gen4 log data is documentation. It is the what happened, and what was observed.


    Flags do support three geometry types encoded in GeoJson format (all other geometry types will be rejected by the API):


    - Point

    - LineString

    - Polygon


    Code of conduct for the API:

    1. All flags are equal and can be routed from any app to all apps supporting flags API.

    2. Flags are digital markers the user places at a location marking it for (future) attention or treatment in a specific way. It is \"setup\" master data in its own right, and not intended to model any more concrete thing than a digital marker.

    3. Because of 1) and 2), flags are NOT intended to be a mechanism for easily adding new entity types into our system.

    4. Flag categories are meaningless to the system.

    5. The system shall not do any automatic decisions based on flag data besides considering:

    \  - flag type (FLAG vs SCOUT)

    \  - geometry type (e.g., points only).

    \  - creation date/last modification date

    \  - global vs field-related

    6. User makes decision what flag categories to show in each app based on manually filtering flag categories.

    7. Clients SHALL not rely on the certain metadata key-values are present in the flags object or not.

    8. Clients SHOULD not display any metadata they cannot interpret.

    9. Clients SHALL not delete, update any metadata they cannot interpret.

    10. Metadata array is updated/patched as a whole. I.e., if client needs to update/delete a certain key, all other key-values SHALL be contained unchanged in the PUT or PATCH request.

    11. Clients SHALL ignore geometries they cannot interpret/process/display or use request parameters to exclude those.\n"
  version: "1.0.0"
  title: "Axiom Public Flags API"
servers:
  - url: "https://partnerapi.deere.com/platform"
paths:
  /organizations/{orgId}/fields/{fieldId}/flags:
    get:
      operationId: "getOrgFieldFlags"
      summary: "List flags for the field"
      tags:
        - "Flags APIs"
      description: "This resource will return a list of flag objects associated with the field."
      security:
        - OAuth2:
            - "ag1"
  /organizations/{orgId}/flagCategories:
    get:
      summary: "List Flags Category Collection"
      operationId: "getFlagCategoriesForOrganization"
      tags:
        - "Flag Categories APIs"
      description: "This resource will return a Flags Category Collection for Organization."
      security:
        - OAuth2:
            - "ag1"
    post:
      operationId: "createFlagCategory"
      summary: "Create a custom category"
      tags:
        - "Flag Categories APIs"
      description: "This resource will create a custom category in the given organization."
      security:
        - OAuth2:
            - "ag3"
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
  /organizations/{orgId}/flagCategories/{categoryId}:
    get:
      operationId: "getFlagCategoryByIdOrgId"
      summary: "Get flag category by id"
      tags:
        - "Flag Categories APIs"
      description: "This resource will return a flag category with the name translated into the specified language. The category can be a reference flagCategory, a master flagCategory created from a referenced flagCategory or a user-defined category."
      security:
        - OAuth2:
            - "ag1"
    put:
      operationId: "updateFlagCategoryByIdOrgId"
      summary: "Update flag category by organization and flag category Id"
      tags:
        - "Flag Categories APIs"
      description: "This resource will update flag category by Id."
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
      security:
        - OAuth2:
            - "ag3"
    delete:
      operationId: "deleteFlagCategoryByIdOrgId"
      summary: "Delete a flag category"
      tags:
        - "Flag Categories APIs"
      description: "This resource will delete a single empty category based on the categoryId and orgId."
      security:
        - OAuth2:
            - "ag3"
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
  /organizations/{orgId}/flagCategories/{categoryId}/flagCategoryPreferences:
    get:
      operationId: "getFlagCategoryPreferencesByIdOrgId"
      summary: "List collection of FlagCategoryPreference"
      tags:
        - "Flag Categories Preferences"
      description: "This endpoint will return a collection of FlagCategoryPreference objects associated with the given flag category. The object with the key \"default\" is created automatically on the 1st access to the flagCategory object by a client. The default preference object shall be initialized with default values: <ul> <li><b>prefKey</b>: \"default\"</li> <li><b>hexColor</b>: \"#FFFFFF\"</li> </ul>"
      security:
        - OAuth2:
            - "ag1"
  /organizations/{orgId}/flagCategoryPreferences/{flagCategoryPreferencesId}:
    get:
      operationId: "getFlagCategoryPreferenceByIdOrgId"
      summary: "View preferences object for a category"
      tags:
        - "Flag Categories Preferences"
      security:
        - OAuth2:
            - "ag1"
      description: "This resource will return the preferences object for the given flag category and org"
    put:
      operationId: "updateFlagCategoryPreferenceByIdOrgId"
      summary: "Update flag category preferences"
      tags:
        - "Flag Categories Preferences"
      description: "This resource will update flag category preferences by Id and Org"
      security:
        - OAuth2:
            - "ag3"
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
  /organizations/{orgId}/flags:
    post:
      operationId: "createFlag"
      tags:
        - "Flags APIs"
      description: "This resource will create a flag in the given organization."
      summary: "Create a flag"
      security:
        - OAuth2:
            - "ag3"
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
    get:
      summary: "View flags list"
      operationId: "getFlagsForOrganization"
      security:
        - OAuth2:
            - "ag1"
      tags:
        - "Flags APIs"
      description: "This resource will return a Flags list for Organization."
  /organizations/{orgId}/flags/{flagId}:
    get:
      summary: "List a flag by org id and Flag id"
      security:
        - OAuth2:
            - "ag1"
      operationId: "getFlagForOrganizationByFlagId"
      tags:
        - "Flags APIs"
      description: "This endpoint will return a flag for a given org and Flag id."
    put:
      operationId: "updateFlagByIdOrgId"
      summary: "Update flag by id"
      tags:
        - "Flags APIs"
      description: "This resource will update flag by Organization and Flag Id."
      security:
        - OAuth2:
            - "ag3"
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
    delete:
      operationId: "deleteFlagByIdOrgId"
      summary: "Delete a flag for a given org"
      tags:
        - "Flags APIs"
      description: "This resource will delete a single flag based on its Id and org id"
      security:
        - OAuth2:
            - "ag3"
      contentType:
        description: "The request body used to create or update a client"
        content:
          application/vnd.deere.axiom.v3+json:
            schema:
              $ref: "#/components/schemas/ContentType"
components:
  securitySchemes:
    OAuth2:
      type: "oauth2"
      flows:
        clientCredentials:
          scopes:
            ag1: "ag1"
            ag3: "ag3"
x-source-documents:
  - endPointName: "flags"
    id: 81
  - endPointName: "flag-categories"
    id: 82
  - endPointName: "flag-categories-preferences"
    id: 83
