/**
 * API server configuration per spec — single source of truth for URL resolution.
 *
 * @generated by scripts/generate-api-servers.ts — do not edit manually
 * Last generated: 2026-04-13T20:34:18.775Z
 *
 * Env coverage matrix (X = supported, - = throws UnsupportedEnvironmentError):
 *
 *                              api  sandboxapi  partnerapi  apicert  apiqa.tal  partnerapicert  partnerapiqa  sandboxapiqa  apidev.tal
 * aemp                          X    X           X           -        -          -               -             -             -
 * assets                        X    X           X           X        X          -               -             -             -
 * boundaries                    X    X           X           X        X          X               X             X             -
 * clients                       X    X           X           X        X          -               -             -             -
 * connection-management         X    X           -           X        X          -               -             -             -
 * crop-types                    X    X           X           X        X          X               X             X             -
 * equipment-measurement         X    -           X           X        X          X               X             X             -
 * equipment                     X    -           X           -        -          -               -             -             -
 * farms                         X    X           X           X        X          -               -             -             -
 * field-operations-api          X    X           X           X        X          X               X             X             -
 * fields                        X    X           X           X        X          -               -             -             -
 * files                         X    X           X           X        X          X               X             X             X
 * flags                         X    X           X           X        X          X               X             X             X
 * guidance-lines                X    X           X           X        X          -               -             -             X
 * harvest-id                    X    X           X           X        X          X               X             X             -
 * machine-alerts                X    X           X           X        X          X               X             X             X
 * machine-device-state-reports  X    X           X           X        X          -               -             -             -
 * machine-engine-hours          X    X           X           X        X          -               -             -             -
 * machine-hours-of-operation    X    X           X           X        X          -               -             -             -
 * machine-locations             X    X           X           X        X          X               X             X             X
 * map-layers                    X    X           X           X        X          -               -             -             -
 * notifications                 X    X           X           X        X          X               X             X             X
 * operators                     X    X           -           X        X          -               -             -             -
 * organizations                 X    X           X           X        X          X               X             X             X
 * partnerships                  X    X           X           X        X          X               X             X             X
 * products                      X    X           X           X        X          -               -             -             X
 * users                         X    X           X           X        X          -               -             -             -
 * webhook                       X    X           X           X        X          -               -             -             X
 *
 * A dash (-) means the env is NOT supported for that spec. Calling a method
 * on that API with that env throws UnsupportedEnvironmentError at request
 * time, before any HTTP call — no silent cross-tier routing.
 */

// ============================================================================
// SpecName — literal union of every OpenAPI spec in specs/fixed/
// ============================================================================

export type SpecName =
  | 'aemp'
  | 'assets'
  | 'boundaries'
  | 'clients'
  | 'connection-management'
  | 'crop-types'
  | 'equipment-measurement'
  | 'equipment'
  | 'farms'
  | 'field-operations-api'
  | 'fields'
  | 'files'
  | 'flags'
  | 'guidance-lines'
  | 'harvest-id'
  | 'machine-alerts'
  | 'machine-device-state-reports'
  | 'machine-engine-hours'
  | 'machine-hours-of-operation'
  | 'machine-locations'
  | 'map-layers'
  | 'notifications'
  | 'operators'
  | 'organizations'
  | 'partnerships'
  | 'products'
  | 'users'
  | 'webhook';

// ============================================================================
// Environment — union of every subdomain seen across templated specs, plus
// the conservatively-unmapped envs so the type covers them (the resolver
// throws UnsupportedEnvironmentError on unmapped envs per spec).
// ============================================================================

export type Environment =
  | 'api'
  | 'sandboxapi'
  | 'partnerapi'
  | 'apicert'
  | 'apiqa.tal'
  | 'partnerapicert'
  | 'partnerapiqa'
  | 'sandboxapiqa'
  | 'apidev.tal';

export const KNOWN_ENVIRONMENTS: readonly Environment[] = [
  'api',
  'sandboxapi',
  'partnerapi',
  'apicert',
  'apiqa.tal',
  'partnerapicert',
  'partnerapiqa',
  'sandboxapiqa',
  'apidev.tal',
] as const;

/**
 * Default environment for new DeereClient instances when config.environment
 * is not specified. 'sandboxapi' is safe-by-default — never silently hits
 * production data.
 */
export const DEFAULT_ENVIRONMENT: Environment = 'sandboxapi';

// ============================================================================
// SpecServerConfig — per-spec URL resolution config
// ============================================================================

export type SpecServerConfig =
  | {
      kind: 'templated';
      /** URL template with `{environment}` placeholder. */
      urlTemplate: string;
      /** Envs declared in the spec's servers.variables.environment.enum. */
      supportedEnvironments: readonly Environment[];
    }
  | {
      kind: 'static';
      /**
       * PARTIAL map — envs we can't confidently serve are OMITTED. Runtime
       * throws UnsupportedEnvironmentError on missing keys. See
       * scripts/generate-api-servers.ts for the env-to-tier classifier.
       */
      urlByEnvironment: Readonly<Partial<Record<Environment, string>>>;
    }
  | {
      kind: 'unavailable';
      /** Human-readable explanation for diagnostics. */
      reason: string;
    };

// ============================================================================
// API_SERVERS — the resolver's lookup table, keyed by spec name
// ============================================================================

export const API_SERVERS: Record<SpecName, SpecServerConfig> = {
  aemp: {
    kind: 'static',
    urlByEnvironment: {
      api: 'https://partneraemp.deere.com',
      partnerapi: 'https://partneraemp.deere.com',
      sandboxapi: 'https://sandboxaemp.deere.com',
    },
  },
  assets: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  boundaries: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'partnerapi',
      'sandboxapi',
      'apicert',
      'partnerapicert',
      'apiqa.tal',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  clients: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  'connection-management': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi'],
  },
  'crop-types': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'partnerapi',
      'sandboxapi',
      'apicert',
      'partnerapicert',
      'apiqa.tal',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  'equipment-measurement': {
    kind: 'static',
    urlByEnvironment: {
      api: 'https://equipmentapi.deere.com/isg',
      partnerapi: 'https://equipmentapi.deere.com/isg',
      apicert: 'https://equipmentapi-cert.deere.com/isg',
      partnerapicert: 'https://equipmentapi-cert.deere.com/isg',
      'apiqa.tal': 'https://equipmentapi-qual.deere.com/isg',
      partnerapiqa: 'https://equipmentapi-qual.deere.com/isg',
      sandboxapiqa: 'https://equipmentapi-qual.deere.com/isg',
    },
  },
  equipment: {
    kind: 'static',
    urlByEnvironment: {
      api: 'https://equipmentapi.deere.com/isg',
      partnerapi: 'https://equipmentapi.deere.com/isg',
    },
  },
  farms: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  'field-operations-api': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'partnerapi',
      'sandboxapi',
      'apicert',
      'partnerapicert',
      'apiqa.tal',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  fields: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  files: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  flags: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  'guidance-lines': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'partnerapi',
      'sandboxapi',
      'api',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
    ],
  },
  'harvest-id': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'partnerapi',
      'sandboxapi',
      'apicert',
      'partnerapicert',
      'apiqa.tal',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  'machine-alerts': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  'machine-device-state-reports': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  'machine-engine-hours': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  'machine-hours-of-operation': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  'machine-locations': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  'map-layers': {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  notifications: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  operators: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi'],
  },
  organizations: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  partnerships: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'sandboxapi',
      'partnerapi',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'partnerapicert',
      'partnerapiqa',
      'sandboxapiqa',
    ],
  },
  products: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'partnerapi',
      'sandboxapi',
      'api',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
    ],
  },
  users: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: ['api', 'apicert', 'apiqa.tal', 'sandboxapi', 'partnerapi'],
  },
  webhook: {
    kind: 'templated',
    urlTemplate: 'https://{environment}.deere.com/platform',
    supportedEnvironments: [
      'api',
      'apicert',
      'apiqa.tal',
      'apidev.tal',
      'sandboxapi',
      'partnerapi',
    ],
  },
};
