/**
 * HATEOAS Route Map
 *
 * Maps API path patterns to their parent resource and link relation name.
 * Used by DeereClient to resolve URLs via HAL link traversal when hateoas mode is enabled.
 *
 * @generated by generate-sdk.ts — do not edit manually
 */

import type { SpecName } from './api-servers.generated.js';

export interface HateoasRoute {
  /** Path pattern of the parent resource (with parameter placeholders) */
  parentPath: string;
  /** HAL link relation name to follow from the parent response */
  rel: string;
  /**
   * Which OpenAPI spec declares the parent resource. Required for cross-spec
   * HATEOAS: if a child lives in equipment.yaml but its parent
   * /organizations/{orgId} is declared in organizations.yaml, the client
   * must fetch the parent via organizations.yaml's host (platform) not
   * equipment.yaml's host (equipmentapi.deere.com/isg).
   */
  parentSpec: SpecName;
}

export const HATEOAS_MAP: Record<string, HateoasRoute> = {
  '/assets/{assetId}/locations': {
    parentPath: '/assets/{assetId}',
    rel: 'locations',
    parentSpec: 'assets',
  },
  '/equipmentMakes/{equipmentMakeId}/equipmentISGTypes': {
    parentPath: '/equipmentMakes/{equipmentMakeId}',
    rel: 'equipmentISGTypes',
    parentSpec: 'equipment',
  },
  '/equipmentMakes/{equipmentMakeId}/equipmentISGTypes/{equipmentISGTypeId}/equipmentModels': {
    parentPath: '/equipmentMakes/{equipmentMakeId}/equipmentISGTypes/{equipmentISGTypeId}',
    rel: 'equipmentModels',
    parentSpec: 'equipment',
  },
  '/equipmentMakes/{equipmentMakeId}/equipmentTypes': {
    parentPath: '/equipmentMakes/{equipmentMakeId}',
    rel: 'equipmentTypes',
    parentSpec: 'equipment',
  },
  '/fieldOperations/{operationId}/boundary': {
    parentPath: '/fieldOperations/{operationId}',
    rel: 'boundary',
    parentSpec: 'field-operations-api',
  },
  '/organizations/{organizationId}/cropTypes': {
    parentPath: '/organizations/{organizationId}',
    rel: 'cropTypes',
    parentSpec: 'organizations',
  },
  '/organizations/{organizationId}/equipment': {
    parentPath: '/organizations/{organizationId}',
    rel: 'equipment',
    parentSpec: 'organizations',
  },
  '/organizations/{organizationId}/varieties': {
    parentPath: '/organizations/{organizationId}',
    rel: 'varieties',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/assets': {
    parentPath: '/organizations/{orgId}',
    rel: 'assets',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/boundaries': {
    parentPath: '/organizations/{orgId}',
    rel: 'boundaries',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/clients': {
    parentPath: '/organizations/{orgId}',
    rel: 'clients',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/clients/{id}/farms': {
    parentPath: '/organizations/{orgId}/clients/{id}',
    rel: 'farms',
    parentSpec: 'clients',
  },
  '/organizations/{orgID}/clients/{id}/fields': {
    parentPath: '/organizations/{orgID}/clients/{id}',
    rel: 'fields',
    parentSpec: 'clients',
  },
  '/organizations/{orgId}/connections': {
    parentPath: '/organizations/{orgId}',
    rel: 'connections',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/farms': {
    parentPath: '/organizations/{orgId}',
    rel: 'farms',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/farms/{farmId}/clients': {
    parentPath: '/organizations/{orgId}/farms/{farmId}',
    rel: 'clients',
    parentSpec: 'farms',
  },
  '/organizations/{orgID}/farms/{id}/fields': {
    parentPath: '/organizations/{orgID}/farms/{id}',
    rel: 'fields',
    parentSpec: 'farms',
  },
  '/organizations/{orgId}/fields': {
    parentPath: '/organizations/{orgId}',
    rel: 'fields',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/fields/{fieldId}/boundaries': {
    parentPath: '/organizations/{orgId}/fields/{fieldId}',
    rel: 'boundaries',
    parentSpec: 'fields',
  },
  '/organizations/{orgId}/fields/{fieldId}/farms': {
    parentPath: '/organizations/{orgId}/fields/{fieldId}',
    rel: 'farms',
    parentSpec: 'fields',
  },
  '/organizations/{orgId}/fields/{fieldId}/fieldOperations': {
    parentPath: '/organizations/{orgId}/fields/{fieldId}',
    rel: 'fieldOperations',
    parentSpec: 'fields',
  },
  '/organizations/{orgId}/fields/{fieldId}/flags': {
    parentPath: '/organizations/{orgId}/fields/{fieldId}',
    rel: 'flags',
    parentSpec: 'fields',
  },
  '/organizations/{orgId}/fields/{fieldId}/guidanceLines': {
    parentPath: '/organizations/{orgId}/fields/{fieldId}',
    rel: 'guidanceLines',
    parentSpec: 'fields',
  },
  '/organizations/{orgID}/fields/{id}/clients': {
    parentPath: '/organizations/{orgID}/fields/{id}',
    rel: 'clients',
    parentSpec: 'fields',
  },
  '/organizations/{orgId}/fields/{id}/mapLayerSummaries': {
    parentPath: '/organizations/{orgId}/fields/{id}',
    rel: 'mapLayerSummaries',
    parentSpec: 'fields',
  },
  '/organizations/{orgId}/files': {
    parentPath: '/organizations/{orgId}',
    rel: 'files',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/flags': {
    parentPath: '/organizations/{orgId}',
    rel: 'flags',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/harvestIdentificationModules': {
    parentPath: '/organizations/{orgId}',
    rel: 'harvestIdentificationModules',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/operators': {
    parentPath: '/organizations/{orgId}',
    rel: 'operators',
    parentSpec: 'organizations',
  },
  '/organizations/{orgId}/users': {
    parentPath: '/organizations/{orgId}',
    rel: 'users',
    parentSpec: 'organizations',
  },
  '/partnerships/{token}/permissions': {
    parentPath: '/partnerships/{token}',
    rel: 'permissions',
    parentSpec: 'partnerships',
  },
  '/users/{userName}/organizations': {
    parentPath: '/users/{userName}',
    rel: 'organizations',
    parentSpec: 'users',
  },
  '/varieties/{erid}/documents': {
    parentPath: '/varieties/{erid}',
    rel: 'documents',
    parentSpec: 'products',
  },
};
